<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="src/style/style.css">
    <title>Mapon</title>
</head>
<body>
    <div id="login-form">
        <h1>Welcome</h1>
        <form method="POST" action="/map">
            <input type="text" name="username" id="username" class="field" placeholder="Username">
            <input type="password" name="pwd" id="pwd" class="field" placeholder="Password">
            <input type="submit" name="enter" id="btn" class="field">
        </form>
    </div>
</body>
</html>
